[build]
command = "npm run build"
publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Cache assets
[[headers]]
  for = "/_generated-og/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=86400, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache news pages
[[headers]]
  for = "/news/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[edge_functions]]
path = "/intranet/*"
function = "auth"

[[edge_functions]]
path = "/auth/callback"
function = "auth"
